// File generated by Antigravity (Manual Setup)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform - '
      'you can reconfigure this by manually adding the keys.',
    );
  }

  // TODO: Replace with your keys from Firebase Console -> Project Settings -> General -> Web App
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIHYpcqbZvkyLW_PcqeJG2ZPP75vqZ51U',
    appId: '1:814782864304:web:b2dad540ed928470775475',
    messagingSenderId: '814782864304',
    projectId: 'scam-guard-9c6ee',
    authDomain: 'scam-guard-9c6ee.firebaseapp.com',
    storageBucket: 'scam-guard-9c6ee.firebasestorage.app',
  );
}
